name: kenali_sister
description: "Merupakan aplikasi pembelajaran komputer"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  flutter_svg: ^1.1.5
  lottie: ^2.3.0
  google_fonts: ^4.0.4
  dio: ^5.0.3
  validatorless: ^1.2.3
  youtube_player_flutter: ^8.1.2
  flutter_pdfview: ^1.3.2
  hive: ^2.2.3
  path_provider: ^2.0.11
  permission_handler: ^11.0.1

  http: ^1.2.1
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustration/
    - assets/images/
